### ISSUE TITLE
How can parameters be overwritten in the yaml file?

### ISSUE THREAD

**Issue by svanschalkwyk** [hellofresh/ansible-oauth2-proxy#1]
Is there an example showing how parameters can be overwritten in the yaml file? 
I have 
`---
- hosts: nodes
  become: yes
  roles:
    - { role: hellofresh.oauth2-proxy }`

When I add parameters to the role, I keep getting yaml errors.
For example, how can I add these?

`oauth2_compress_filename                 : "{{ oaut2_proxy_http | basename }}"
oauth2_filename                          : "{{ oauth2_compress_filename |replace('.tar.gz', '') }}"
oauth2_proxy_config                      :
    http_address                         : "127.0.0.1:5000"
    upstreams                            : [ "127.0.0.1:6060" ]'

Much appreciated.

**Comment by ahelal** [comment]
@svanschalkwyk You can override variables in various way in Ansible. check Ansible doc for [variable precendee](http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable). You can use any method that  has a higher precedence then role defaults (group_vars,hosts_vars or vars in the play)

Example play
```yaml
---
hosts: nodes
become: yes
vars:
    oauth2_host                              : "example.com"
    oauth2_proxy_config                      :
        http_address                         : "0.0.0.0:8000"
        upstreams                            : [ "http://somedomain-upsteam-domain" ]
        cookie_secret                        : "{{ oauth_proxy_cookie_secret }}"
        client_id                            : "{{ oauth_proxy_client_id }}"
        client_secret                        : "{{ oauth_proxy_client_secret }}"
        redirect_url                         : "https://{{ oauth2_host }}/oauth2/callback"

    oauth2_config_cmdline_args               : >
                                               -provider=google
                                               -email-domain=example-email.com
                                               -cookie-secure=true
                                               -cookie-domain={{ oauth2_host }}
                                               -cookie-expire=24h
roles:
{ role: hellofresh.oauth2-proxy }`
```
